title: Paarth Parekh
logo: "/images/Profile (2).jpeg?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Technical Implementation Consultant at Charles River Development. Expert in Financial Software, ETL, and Data Science.
  <br> <br>
  Georgia Institute of Technology <br>
  Master of Science in Bioinformatics <br> 
  GPA: 4.0/4.0 <br>
  <br><br>
  <a href="https://www.linkedin.com/in/paarth-parekh-357123147/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
